dist: trusty
language: R
cache: packages
addons:
  apt:
    update:
    - true
    sources:
    - sourceline: ppa:cran/poppler
    packages:
    - libpoppler-cpp-dev
r_packages:
- devtools
r_github_packages:
- metrumresearchgroup/covrpage  
- metrumresearchgroup/pkgdown
after_success:
- Rscript -e 'covr::codecov()'
- Rscript -e 'devtools::install(); covrpage::covrpage_ci()'
- Rscript -e 'pkgdown::build_site()'
deploy:
  provider: pages
  skip-cleanup: true
  github-token: "$GITHUB_PAT"
  keep-history: true
  local-dir: docs
  on:
    branch: master
env:
  global:
    secure: BaZAPO2T4IxVKijEfg9w26krCRsqtQ4ytB1vyy/66Dtn00VwVEUYdOPbe5w6m5AXlJ0Wjx4mH9Zyqw8Hqdrb2lYqcwCIANVdhhLzdANFYm398HF+8d6CSP4Pne2X+p5Ly6sIIR/enbt0ffgI/fab1jgHmEQoYd+pzFkgyMAb52Zww/PWRGrvMp2lrZhEEvjGI0RNrkPU5loWIY66KRG+qyAnMMeAFY208ACKuKr7AJjQ6jKHIxeFCjIcgtwrmXfXjjBdo91cI2qgBqIvab/JVxl52IAGU6E7Y7pX/a89CJPo3jFRK6nJiweAAqHaYNOaUzp5xnPF6cNBsulZ2KwZvF2LS8pIUhZJKSqNL+FDssU3KfGVObU3w0W2FeT8gMWyN/+Jul/u1Rd94i/rOs3LZStPZ3IPSz8z9MMYlVnBECwR5jQlFJoEBRoAhAsTWw7WJ8wfS6tYdeRrQ56lQXxToRcADloj1E9JUu5nQAAOVQ6o023H0SgpP79SOWEMSBpdsCg5STjZlOA4F4lMF/EdAEEbiKSmShOeOvX058byu1QX1l7U7X87ku+2irxeJHRNhNJaMaGd8zsHCH5IwcSOSUanYM5VpawmLsd7w6CDOGVpK3RZRo9MsuMFOnk5l13FJg6ZMMsutSQMoqcTe9j9BYO8SwD6aBs2lMAZHAqxnI8=
notifications:
  slack:
    secure: FGaPE1ablWY+kz8jDLOdxQjKspDJYJv0P3sW8fQxUHJ8FDOwbCfsOBN2PxVx0jwK+iwnGGg0M8afMuIdmCXO6EOYcy79OXijsPHMCBx3s20CuCYvnNX3hBJIsb42XCUofvZNyDN9FJeyuACZ+WHRvJJQ7bMBjWMPIQC+PSTenGKRY4+jjSlN3Sh/CK2wOHWJ0hmRWfcdJkTFZ6+B9w2X02p/TVm3XEh1GzPXKjI16gNlsQmLcKbQk4v1WwAOhN+sBfwb5EF/S/qxITxyMWnSJDVSqeh9vn+VzV9l/SGHn2I//CN1l5aQC29//REswS5l95HRd95diWCKIAVBUEsyJQZSFfNr6xYcO+tAihuM7Ms3hIrHGknxSr16VUCv9HC4qjfxUL9Am9556iGwbL1QuK1ZCWRayAv7LTQ4plDlkQVjvTFFxGxU7GWiS+dP9JRVFmV9ICejCDTfmGfta0e6J31icYOFIDYGhtTtpgg1UrjrpKSWG3MiePuoLYlXqdgAfbc9xZRsxi8DRurN0ZYFESlKkTIeJQG27yJxkX0XXQPcVbKrk9QqMPMLwNWwaGs9H+HXIac5iPIZ61Ib7oDKdFuPxxZEbNK7dExXGCIlQ90Ln8quv4Hg9Swfrd5g7FukpPcrQw26nSHx0OvbCDD8uuvF+fbY51CJRW5W5PrSckI=
